# 服务端口
server:
  port: 8001

spring:
  # 服务名
  application:
    name: service-edu
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_edu?serverTimezone=GMT%2B8
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis-plus 配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
#  level:
#    root: info
  file:
    path: ./log/service-edu
thread:
  pool:
    core-pool-size: 6
    max-pool-size: 12
    keep-alive-seconds: 0
    queue-capacity: 12
    thread-name-format: edu-async-%02d
