server:
  port: 8002
  servlet:
    context-path: /oss

spring:
  application:
    name: service-oss
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
logging:
  file:
    path: ./log/service-oss

aliyun:
  oss:
    endpoint: jfkdjk
    bucket-name: kfjdkfj
    key-id: fdkfjkd
    key-secret: fjdfjdk
